/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        black: "#000",
        "light-purple": "#f0ecf9",
        "light-purple1": "rgba(138, 79, 255, 0.14)",
        black: "#000",
        gray: "rgba(0, 0, 0, 0.36)",          
        dimgray: "#655f5f",
        lavender: "#f0ecf9",
        semitrans:"rgba(0, 0, 0, 0.5)",
        lightsteelblue: "#a0aec0",
        gray1: "#171923",
        blueviolet: "rgba(138, 79, 255, 0.14)",
        mediumslateblue: "#9e6dfe",
        mediumblue: "#4400ca",
        tomato: "#ff4343",
        textpurple: "rgba(138, 79, 255, 1)",
        blue: "#1400ff",
      },
      spacing: {},
      fontFamily: {
        "droid-sans": "'Droid Sans'",
        acme: "Acme",
        inter: "Inter",
        "carter-one": "'Carter One'",
        mulish: "Mulish",
        content: "Content",
        arimo: "Arimo",
        lato: "Lato",
        "dm-sans": "'DM Sans'",
      },
      borderRadius: {
        "81xl": "100px",
        "11xl": "30px",
        xl: "20px",
        "31xl": "50px",
        lgi: "19px",
        "10xl": "1.81rem",
        "19xl": "2.38rem",
        inherit: "inherit",
      },
    },
    fontSize: {
      lg: "18px",
      inherit: "inherit",
      smi: "0.81rem",
      xs: "0.75rem",
      base: "1rem",
      "3xl": "1.38rem",
      sm: "0.88rem",
    },
  },
  corePlugins: {
    preflight: false,
  },
};
